# A basic workflow 

name: Update-data

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "13 12 */2 * *" # Every two days at 12:13 PM
    # - cron: */5 * * * *	#Execute a command every five minutes.
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
 autoscrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Load repo and install R
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with: 
          r-version: '4.2.2' # The R version to download (if necessary) and use.
          # r-version: ${{ matrix.R }}
          # Enable RStudio Package Manager to speed up package installation
          use-public-rspm: true
      # with:
      #   r-version: ${{ matrix.config.r }} 
      #   # Enable RStudio Package Manager to speed up package installation
      #   use-public-rspm: true

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("tidyverse")'

    # Run R script
    - name: Scrape
      run: Rscript src/PullBB.R
      
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add Figures/*
        git commit -am "GH ACTION Headlines $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
